header_template=My Teletext Service %d %b %H:%M/%S
initial_teletext_page=100:3F7F
status_display=MY CUSTOM SERVICE
lines_per_field=16
row_adaptive_mode=false
network_identification_code=0000
country_network_identification=0000